services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: easystudy-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - /app/.venv
      - /app/__pycache__

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: easystudy-frontend
    ports:
      - "5173:80"
    env_file:
      - ./frontend/.env
    restart: unless-stopped
    depends_on:
      - backend
