services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env.dev
    volumes:
      - ./backend:/app
      - /app/.venv
      - /app/__pycache__

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_MODE=dev
    env_file:
      - ./frontend/.env.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/dist
