"""Add summary to document

Revision ID: 875afd8e0b2e
Revises: 6e2d1d2b7c4a
Create Date: 2026-03-28 16:00:35.361232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '875afd8e0b2e'
down_revision: Union[str, Sequence[str], None] = '6e2d1d2b7c4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'summary')
    # ### end Alembic commands ###
